version: '3.8'

services:
  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmark-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bookmark-network
  
  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: bookmark-postgres
    restart: unless-stopped
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-bookmarks}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-bookmarks}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bookmark-network

# Volumes
volumes:
  postgres-data:
    driver: local

# Networks
networks:
  bookmark-network:
